basePath: /api/v1/
definitions:
  core.Course:
    properties:
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  service.CreateCourseInput:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  utils.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for Course Watch App
  title: Course Watch API
  version: "1.0"
paths:
  /courses/:
    post:
      consumes:
      - application/json
      description: Creates a new Course entity
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/service.CreateCourseInput'
      produces:
      - application/json
      responses:
        "201":
          description: The generated id is returned in Location header
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Creates a new Course entity
      tags:
      - courses
  /courses/{id}:
    get:
      consumes:
      - application/json
      description: get course by id
      parameters:
      - description: course id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Get Course By course id
      tags:
      - courses
securityDefinitions:
  AdminAuth:
    in: header
    name: Authorization
    type: apiKey
  StudentsAuth:
    in: header
    name: Authorization
    type: apiKey
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
